<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class FiturSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      //fitur di kategori harga pemula
      DB::table('fitur')->insert([
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Rekap Transaksi',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Jurnal',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Buku Besar',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan daftar aset',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Keuangan :',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Posisi Keuangan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Laba Rugi Komprehensif',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perubahan ekuitas',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Arus Kas',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Catatan Laporan Keuangan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perpajakan :',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 21',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 22',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => ' PPh Pasal 23',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 25',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 26',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 29',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 4 (2)',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Final',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPN',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Dll',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat e-billing',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membayarkan Pajak',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT PPh Masa',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT Tahunan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Keuangan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Pajak',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Print Laporan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Backup Laporan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Pengarsipan Laporan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Visit Perusahaan',
          'harga_id' => 3,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ]
      ]);
      //fitur di kategori harga profesional
      DB::table('fitur')->insert([
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Rekap Transaksi',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Jurnal',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Buku Besar',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan daftar aset',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Keuangan :',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Posisi Keuangan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Laba Rugi Komprehensif',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perubahan ekuitas',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Arus Kas',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Catatan Laporan Keuangan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perpajakan :',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 21',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 22',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 23',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 25',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 26',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 29',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 4 (2)',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Final',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPN',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Dll',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat e-billing',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membayarkan Pajak',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT PPh Masa',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT Tahunan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Keuangan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Pajak',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Print Laporan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Backup Laporan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Pengarsipan Laporan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Visit Perusahaan',
          'harga_id' => 2,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ]
      ]);
      //fitur dikategori harga Bisnis
      DB::table('fitur')->insert([
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Rekap Transaksi',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Jurnal',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Buku Besar',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan daftar aset',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Keuangan :',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Posisi Keuangan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Laba Rugi Komprehensif',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perubahan ekuitas',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Arus Kas',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Catatan Laporan Keuangan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Laporan Perpajakan :',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'kosong',
          'menu' => 'besar',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 21',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 22',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => ' PPh Pasal 23',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 25',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 26',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 29',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Pasal 4 (2)',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPh Final',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'PPN',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Dll',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'sub',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat e-billing',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membayarkan Pajak',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT PPh Masa',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Membuat & Melapor SPT Tahunan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Keuangan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Perencanaan Pajak',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Print Laporan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Backup Laporan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Pengarsipan Laporan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'tidak',
          'menu' => 'biasa',
        ],
        [
          'id' => (string) Str::uuid(),
          'fitur' => 'Visit Perusahaan',
          'harga_id' => 1,
          'tampilkan' => 'iya',
          'ada' => 'iya',
          'menu' => 'biasa',
        ]
      ]);
    }
}
